/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.*;
import clases.*;
import com.mysql.cj.protocol.Message;
import java.awt.HeadlessException;
import java.util.LinkedList;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marce
 */
public class panel2 extends javax.swing.JFrame {

    public panel2() {
        initComponents();
        llenar_listamotor();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_motor = new javax.swing.JList<>();
        txt_codmotor = new javax.swing.JTextField();
        txt_cilindrajemotor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_crearmotor = new javax.swing.JButton();
        btn_buscarmotor = new javax.swing.JButton();
        btn_eliminarmotor = new javax.swing.JButton();
        btn_actualizarmotor = new javax.swing.JButton();
        cb_combustible_motor = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_modelocarro = new javax.swing.JTextField();
        txt_aniofabcarro = new javax.swing.JTextField();
        cb_numcambioscarro = new javax.swing.JComboBox<>();
        txt_colorcarro = new javax.swing.JTextField();
        cb_numruedascarro = new javax.swing.JComboBox<>();
        cb_rinescarro = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        javax.swing.JList<String> list_carros = new javax.swing.JList<>();
        btn_crearcarro = new javax.swing.JButton();
        btn_buscarcarro = new javax.swing.JButton();
        btn_actualizarcarro = new javax.swing.JButton();
        btn_eliminarcarro = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        chb_airbag = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        cb_motores = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_modelomoto = new javax.swing.JTextField();
        txt_aniofabmoto = new javax.swing.JTextField();
        cb_numcambiosmoto = new javax.swing.JComboBox<>();
        txt_colormoto = new javax.swing.JTextField();
        cb_numruedasmoto = new javax.swing.JComboBox<>();
        cb_rinesmoto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JList<String> list_motos = new javax.swing.JList<>();
        btn_crearmoto = new javax.swing.JButton();
        btn_buscarmoto = new javax.swing.JButton();
        btn_actualizarmoto = new javax.swing.JButton();
        btn_eliminarmoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(lista_motor);

        txt_cilindrajemotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cilindrajemotorActionPerformed(evt);
            }
        });

        jLabel2.setText("CILINDRAJE");

        jLabel3.setText("CODIGO");

        jLabel4.setText("COMBUSTIBLE");

        btn_crearmotor.setText("CREAR");
        btn_crearmotor.setName(""); // NOI18N
        btn_crearmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearmotorActionPerformed(evt);
            }
        });

        btn_buscarmotor.setText("BUSCAR");
        btn_buscarmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarmotorActionPerformed(evt);
            }
        });

        btn_eliminarmotor.setText("ELIMINAR");
        btn_eliminarmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarmotorActionPerformed(evt);
            }
        });

        btn_actualizarmotor.setText("ACTUALIZAR");
        btn_actualizarmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarmotorActionPerformed(evt);
            }
        });

        cb_combustible_motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GASOLINA", "ACPM" }));
        cb_combustible_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_combustible_motorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cilindrajemotor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_combustible_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_crearmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btn_buscarmotor)
                        .addGap(26, 26, 26)
                        .addComponent(btn_actualizarmotor)
                        .addGap(36, 36, 36)
                        .addComponent(btn_eliminarmotor)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cilindrajemotor)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_combustible_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_crearmotor)
                            .addComponent(btn_buscarmotor)
                            .addComponent(btn_actualizarmotor)
                            .addComponent(btn_eliminarmotor)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tab.addTab("MOTORES", jPanel1);

        jLabel11.setText("Num Cambios");

        jLabel12.setText("Num Ruedas");

        jLabel13.setText("Año Fabricacion");

        jLabel14.setText("Color");

        jLabel15.setText("Modelo");

        jLabel16.setText("Tipo Rines");

        cb_numcambioscarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", ">6" }));

        cb_numruedascarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "6", ">6" }));

        cb_rinescarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasicos", "luko" }));

        jScrollPane3.setViewportView(list_carros);

        btn_crearcarro.setText("CREAR");
        btn_crearcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearcarroActionPerformed(evt);
            }
        });

        btn_buscarcarro.setText("BUSCAR");
        btn_buscarcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarcarroActionPerformed(evt);
            }
        });

        btn_actualizarcarro.setText("ACTUALIZAR");
        btn_actualizarcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarcarroActionPerformed(evt);
            }
        });

        btn_eliminarcarro.setText("ELIMINAR");

        jLabel17.setText("Airbag");

        jLabel18.setText("COD Motor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_aniofabcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(75, 75, 75)
                                    .addComponent(txt_modelocarro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel16))
                                        .addGap(44, 44, 44))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_numcambioscarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_rinescarro, 0, 115, Short.MAX_VALUE)
                                    .addComponent(cb_motores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14)
                                .addGap(65, 65, 65)
                                .addComponent(txt_colorcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chb_airbag)
                                    .addComponent(cb_numruedascarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_crearcarro)
                        .addGap(36, 36, 36)
                        .addComponent(btn_buscarcarro)
                        .addGap(37, 37, 37)
                        .addComponent(btn_actualizarcarro)
                        .addGap(47, 47, 47)
                        .addComponent(btn_eliminarcarro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_modelocarro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(txt_aniofabcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cb_numcambioscarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txt_colorcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_numruedascarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cb_rinescarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(chb_airbag))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_motores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearcarro)
                    .addComponent(btn_buscarcarro)
                    .addComponent(btn_actualizarcarro)
                    .addComponent(btn_eliminarcarro))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tab.addTab("CARRO", jPanel3);

        jLabel5.setText("Num Cambios");

        jLabel6.setText("Num Ruedas");

        jLabel7.setText("Año Fabricacion");

        jLabel8.setText("Color");

        jLabel9.setText("Modelo");

        jLabel10.setText("Tipo Rines");

        cb_numcambiosmoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5" }));

        cb_numruedasmoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        cb_rinesmoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasicos", "luko" }));

        jScrollPane2.setViewportView(list_motos);

        btn_crearmoto.setText("CREAR");

        btn_buscarmoto.setText("BUSCAR");

        btn_actualizarmoto.setText("ACTUALIZAR");

        btn_eliminarmoto.setText("ELIMINAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_aniofabmoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(75, 75, 75)
                                    .addComponent(txt_modelomoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_numcambiosmoto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_rinesmoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(cb_numruedasmoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel8)
                                .addGap(65, 65, 65)
                                .addComponent(txt_colormoto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btn_crearmoto)
                        .addGap(36, 36, 36)
                        .addComponent(btn_buscarmoto)
                        .addGap(37, 37, 37)
                        .addComponent(btn_actualizarmoto)
                        .addGap(47, 47, 47)
                        .addComponent(btn_eliminarmoto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_modelomoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_aniofabmoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cb_numcambiosmoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_colormoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cb_numruedasmoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cb_rinesmoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_crearmoto)
                            .addComponent(btn_buscarmoto)
                            .addComponent(btn_actualizarmoto)
                            .addComponent(btn_eliminarmoto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tab.addTab("MOTO", jPanel2);

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE VEHICULOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//CRUD MOTOR
    private void txt_cilindrajemotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cilindrajemotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cilindrajemotorActionPerformed

    private void btn_crearmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearmotorActionPerformed
        try {
            String codigo = txt_codmotor.getText();
            int cilindraje = Integer.parseInt(txt_cilindrajemotor.getText());
            String tipo_comb = (String) cb_combustible_motor.getSelectedItem();

            cls_motor motor = new cls_motor(codigo, cilindraje, tipo_comb);
            controller_motor Cmotor = new controller_motor();
            if (Cmotor.crear_motor(motor) == true) {
                JOptionPane.showMessageDialog(this, "Registro exitoso");
                txt_codmotor.setText(codigo);

            } else {
                JOptionPane.showMessageDialog(this, "Registro fallido");
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Datos no validos");
        }

    }//GEN-LAST:event_btn_crearmotorActionPerformed

    private void btn_buscarmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarmotorActionPerformed
        // TODO add your handling code here:
        String codigo = txt_codmotor.getText();
        controller_motor Cmotor = new controller_motor();
        cls_motor motorX;
        motorX = (cls_motor) Cmotor.buscar_motor(codigo);
        if (motorX == null) {
            JOptionPane.showMessageDialog(this, "Registro Faltante");
        } else {
            JOptionPane.showMessageDialog(this, "Registro Encontrado");
            txt_cilindrajemotor.setText(motorX.getCilindraje_cc() + "");
            cb_combustible_motor.setSelectedItem(motorX.getTipo_combustible());
        }

    }//GEN-LAST:event_btn_buscarmotorActionPerformed

    private void btn_actualizarmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarmotorActionPerformed
        // TODO add your handling code here:
        try {
            String codigo = txt_codmotor.getText();
            int cilindraje = Integer.parseInt(txt_cilindrajemotor.getText());
            String tipo_comb = (String) cb_combustible_motor.getSelectedItem();

            cls_motor motor = new cls_motor(codigo, cilindraje, tipo_comb);
            controller_motor Cmotor = new controller_motor();
            if (Cmotor.actualizar_motor(motor)) {
                JOptionPane.showMessageDialog(this, "Registro anctializado exitosamente");
                txt_codmotor.setText(codigo);
            } else {
                JOptionPane.showMessageDialog(this, "El Registro no pudo ser actualizado");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Datos no validos");
        }

    }//GEN-LAST:event_btn_actualizarmotorActionPerformed

    private void btn_eliminarmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarmotorActionPerformed
        // TODO add your handling code here:
        String codigo = txt_codmotor.getText();
        controller_motor Cmotor = new controller_motor();
        LinkedList<cls_motor> motorX;
        motorX = Cmotor.buscarEliminar_motor(codigo);
        if (motorX == null) {
            JOptionPane.showMessageDialog(this, "No fue posible eliminar el registro");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog(null, "ELIMINAR REGISTRO:  \n Codigo: " + codigo + "\n Cilindraje: " + motorX.get(0).getCilindraje_cc() + "\n Combustible: " + motorX.get(0).getTipo_combustible(), "Warning", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {
                if (Cmotor.eliminar_motor(codigo)) {
                    JOptionPane.showMessageDialog(this, "Se presento un error al eliminar el registro.");
                } else {
                    JOptionPane.showMessageDialog(this, "Registro Eliminado");
                }
            }

        }


    }//GEN-LAST:event_btn_eliminarmotorActionPerformed

    private void llenar_listamotor() {
        DefaultListModel model = new DefaultListModel();
        controller_motor Lmotor = new controller_motor();
        LinkedList<cls_motor> motorlista;
        motorlista = Lmotor.listado_motor();
        String data = "Codigo - Cilindraje_cc - combustible";
        model.add(0, data);
        int index = 1;
        for (cls_motor lmotor : motorlista) {
            data = lmotor.getCodigo() + " -      " + lmotor.getCilindraje_cc() + "      -   " + lmotor.getTipo_combustible();
            model.add(index, data);
            index++;
            String data1 = lmotor.getId() + "-" + lmotor.getCodigo();
            cb_motores.addItem(data1);
        }
        lista_motor.setModel(model);

    }

    private void cb_combustible_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_combustible_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_combustible_motorActionPerformed

    //CRUD CARRO
    private void btn_crearcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearcarroActionPerformed
        // TODO add your handling code here:
        try {
            String modelo = txt_modelocarro.getText();
            String aniofab = txt_aniofabcarro.getText();
            String color = txt_colorcarro.getText();
            String num_cambios = (String) cb_numcambioscarro.getSelectedItem();
            String num_ruedas = (String) cb_numruedascarro.getSelectedItem();
            String tip_rines = (String) cb_rinescarro.getSelectedItem();
            boolean airbag = chb_airbag.isSelected();
            String cod_motorcarro = cb_motores.getSelectedItem().toString();
            List<String> MList = Arrays.asList(cod_motorcarro.split("-"));
            controller_motor Cmotor = new controller_motor();
            int motor = Integer.parseInt(MList.get(0));
            cls_carro carro = new cls_carro(airbag, modelo, tip_rines, num_cambios, num_ruedas, aniofab, color, motor);
            controller_carro Ccarro = new controller_carro();
            if (Ccarro.crear_carro(carro) == true) {
                JOptionPane.showMessageDialog(this, "Registro exitoso");
            } else {
                JOptionPane.showMessageDialog(this, "Registro fallido");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Datos no validos");
        }
    }//GEN-LAST:event_btn_crearcarroActionPerformed

    private void btn_buscarcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarcarroActionPerformed
        String modelocarro = txt_modelocarro.getText();
        controller_carro Ccarro = new controller_carro();
        cls_carro carroX;
        carroX = (cls_carro) Ccarro.buscar_carro(modelocarro);
        if (carroX == null) {
            JOptionPane.showMessageDialog(this, "Registro Faltante");
        } else {
            JOptionPane.showMessageDialog(this, "Registro Encontrado");
            txt_aniofabcarro.setText(carroX.getAnnio_fabricacion() + "");
            txt_colorcarro.setText(carroX.getColor() + "");
            cb_numcambioscarro.setSelectedItem(carroX.getNum_cambios());
            cb_numruedascarro.setSelectedItem(carroX.getNum_ruedas());
            System.out.println("RINES: "+carroX.getTipo_rines()+" ID: "+carroX.getId_motor());
            cb_rinescarro.setSelectedItem(carroX.getTipo_rines());
            cb_motores.setSelectedItem(carroX.getId_motor());
        }

    }//GEN-LAST:event_btn_buscarcarroActionPerformed

    private void btn_actualizarcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarcarroActionPerformed
        // TODO add your handling code here:
        try {
            String modelo = txt_modelocarro.getText();
            String aniofab = txt_aniofabcarro.getText();
            String color = txt_colorcarro.getText();
            String num_cambios = (String) cb_numcambioscarro.getSelectedItem();
            String num_ruedas = (String) cb_numruedascarro.getSelectedItem();
            String tip_rines = (String) cb_rinescarro.getSelectedItem();
            boolean airbag = chb_airbag.isSelected();
            String cod_motorcarro = cb_motores.getSelectedItem().toString();
            List<String> MList = Arrays.asList(cod_motorcarro.split("-"));

            controller_motor Cmotor = new controller_motor();
            int motor = Integer.parseInt(MList.get(0));
            cls_carro carro = new cls_carro(airbag, modelo, tip_rines, num_cambios, num_ruedas, aniofab, color, motor);
            controller_carro Ccarro = new controller_carro();
            
            if (Ccarro.actualizar_carro(carro)) {
                JOptionPane.showMessageDialog(this, "Registro actualizado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "El Registro no pudo ser actualizado");
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Datos no validos");
        }
    }//GEN-LAST:event_btn_actualizarcarroActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarcarro;
    private javax.swing.JButton btn_actualizarmoto;
    private javax.swing.JButton btn_actualizarmotor;
    private javax.swing.JButton btn_buscarcarro;
    private javax.swing.JButton btn_buscarmoto;
    private javax.swing.JButton btn_buscarmotor;
    private javax.swing.JButton btn_crearcarro;
    private javax.swing.JButton btn_crearmoto;
    private javax.swing.JButton btn_crearmotor;
    private javax.swing.JButton btn_eliminarcarro;
    private javax.swing.JButton btn_eliminarmoto;
    private javax.swing.JButton btn_eliminarmotor;
    private javax.swing.JComboBox<String> cb_combustible_motor;
    private javax.swing.JComboBox<String> cb_motores;
    private javax.swing.JComboBox<String> cb_numcambioscarro;
    private javax.swing.JComboBox<String> cb_numcambiosmoto;
    private javax.swing.JComboBox<String> cb_numruedascarro;
    private javax.swing.JComboBox<String> cb_numruedasmoto;
    private javax.swing.JComboBox<String> cb_rinescarro;
    private javax.swing.JComboBox<String> cb_rinesmoto;
    private javax.swing.JCheckBox chb_airbag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista_motor;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField txt_aniofabcarro;
    private javax.swing.JTextField txt_aniofabmoto;
    private javax.swing.JTextField txt_cilindrajemotor;
    private javax.swing.JTextField txt_codmotor;
    private javax.swing.JTextField txt_colorcarro;
    private javax.swing.JTextField txt_colormoto;
    private javax.swing.JTextField txt_modelocarro;
    private javax.swing.JTextField txt_modelomoto;
    // End of variables declaration//GEN-END:variables
}
